name: 📦 Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # Ex: v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: 📦 Restore
        run: dotnet restore

      - name: 🛠️ Build
        run: dotnet build --configuration Release --no-restore

      - name: 📦 Pack com versão da tag (sem 'v')
        run: |
          VERSION=${GITHUB_REF##*/}
          VERSION=${VERSION#v}
          echo "📦 Empacotando pacote com versão: $VERSION"
          dotnet pack --configuration Release --no-build --output ./artifacts /p:Version=$VERSION

      - name: 🚀 Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
